pango_assignment.cache.csv.gz, pango_usher.csv.gz
pango_assignment.cache.csv.gz contains full CSV output indexed by aligned & masked sequence hash, stored by git LFS.  Intended to work with current handle_cache branch of pangolin.
=> hash assignments for testing with pangolin handle_cache branch

pangolin_assignment/pango_assignment.cache.csv.gz
I added ~250k unique to COG-UK and ~100k unique to GenBank.  
When combining all together, I sorted by the second column (lineage; used `sort -t, -k2`) so that there would be more local similarity in the uncompressed CSV, hoping that would help compression, and indeed the compressed file size reduced from the previous commit's 143563664 to 122564273 (~17% smaller despite having ~6% more lines).
When trimming to only the first two fields (hash and lineage), sorting by hash (just `sort`) and compressing, the final size was 116426490, but sorting by lineage (`sort -t, -k2`) and compressing reduced the size further to 112018843, still not all that much smaller than the lineage-sorted full results.  Looks like it'll be git-lfs either way.  (I guess we could use truncated md5sums instead of the …
=> Adding assignments for hashes unique to COG-UK & GenBank (downloaded 2022-01-20)

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
In order to test some changes to pangolin branch handle_cache that will update how the cache file is installed, updated and used, I need pangolin-assignment to have a release that is in sync with pangolin-data.  This PR adds a new file usher_assignments.cache.csv.gz and sets __version__ to v1.2.127 .  usher_assignments.cache.csv.gz has pangolin v4.0 output columns, although it is currently derived from the output of pangolin 3.1.20 so its qc_notes column is empty.
=> Release for testing

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.2.127 on GISAID sequences downloaded through 2022-03-16.
Using Rachel's new --skip-scorpio flag and restricting columns so scorpio from runtime is used.
=> Updated pangolin v4.0 cache file for testing (reduced column set, new sequences).

pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.2.133 on GISAID sequences downloaded through 2022-03-30
=> v1.2.133 update

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.11 on GISAID sequences downloaded through 2022-06-22
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/) using the following software versions:
pangolin: 4.0.6 (with --skip-scorpio flag and --usher-tree <[v1.9 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.9/pangolin_data/data/lineageTree.pb)> file prior to v1.9 release)
usher: v0.5.4
faToVcf: bioconda 426
gofasta: bioconda 1.0.0
minimap2: bioconda 2.24 (--version --> 2.24-r1122)
=> Prerelease v1.11 branch

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Move changes from prerelease branch to master.
Assignment cache from pango-designation v1.11 on GISAID sequences downloaded through 2022-06-22
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/) using the following software versions:
pangolin: 4.0.6 (with --skip-scorpio flag and --usher-tree <[v1.9 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.9/pangolin_data/data/lineageTree.pb)> file prior to v1.9 release)
usher: v0.5.4
faToVcf: bioconda 426
gofasta: bioconda 1.0.0
minimap2: bioconda 2.24 (--version --> 2.24-r1122)
=> Prerelease v1.11

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.12 on GISAID sequences downloaded through 2022-07-11
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/) using the following software versions:
pangolin: 4.1.1 (with --skip-scorpio flag and --usher-tree <[v1.12 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.12/pangolin_data/data/lineageTree.pb)> file prior to v1.12 release)
usher: v0.5.4
faToVcf: bioconda 426
gofasta: bioconda 1.0.0
minimap2: bioconda 2.24 (--version --> 2.24-r1122)
=> Prerelease v1.12 branch

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.13 on GISAID sequences downloaded through 2022-08-01
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.13 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.13/pangolin_data/data/lineageTree.pb)> file prior to v1.13 release
```
pangolin: 4.1.2
usher 0.5.4
gofasta 1.0.0
faToVcf: 426
```
=> Prerelease v1.13 branch

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.14 on GISAID sequences downloaded through 2022-08-21
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.14 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.14/pangolin_data/data/lineageTree.pb)> file prior to v1.14 release
```
pangolin: 4.1.2
usher 0.5.4
gofasta 1.0.0
faToVcf: 426
```
=> Prerelease v1.14 branch

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.18 on GISAID sequences downloaded through 2023-01-11
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.18 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.18/pangolin_data/data/lineageTree.pb)> file prior to v1.18 release.
```
pangolin: 4.2
usher 0.6.1
gofasta 1.1.0
faToVcf: 426
```
=> Prerelease v1.18

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.18.1 on GISAID sequences downloaded through 2023-02-16
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.18.1 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.18.1/pangolin_data/data/lineageTree.pb)> file prior to v1.18.1 release.
```
pangolin: 4.2
usher 0.6.2
gofasta 1.1.0
faToVcf: 426
```
=> Prerelease v1.18.1

pangolin_assignment/__init__.py
pangolin-data required a little [update](https://github.com/cov-lineages/pangolin-data/pull/36) to v1.18.1.1; no change required here beyond keeping the latest release versions consistent.
=> minor version bump v1.18.1.1 to stay in sync with pangolin-data

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.19 on GISAID sequences downloaded through 2023-03-30
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.19 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.19/pangolin_data/data/lineageTree.pb)> file prior to v1.19 release.
```
pangolin: 4.2
usher 0.6.2
gofasta 1.1.0
faToVcf: 426
```
=> Prerelease v1.19

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.20 on GISAID sequences downloaded through 2023-05-22
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.20 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.20/pangolin_data/data/lineageTree.pb)> file prior to v1.20 release.
```
pangolin: 4.3
usher 0.6.2
gofasta 1.1.0
faToVcf: 426
```
=> Prerelease v1.20

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.21 on GISAID sequences downloaded through 2023-06-21
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.21 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.21/pangolin_data/data/lineageTree.pb)> file prior to v1.21 release.
```
pangolin: 4.3
usher 0.6.2
gofasta 1.2.0
faToVcf: 426
```
=> Prerelease v1.21

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.22 on GISAID sequences downloaded through 2023-08-17
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.22 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.22/pangolin_data/data/lineageTree.pb)> file prior to v1.22 release.
```
usher 0.6.2
gofasta 1.2.0
faToVcf: 426
```
=> Prerelease v1.22

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.23 on GISAID sequences downloaded through 2023-10-16
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.23 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.23/pangolin_data/data/lineageTree.pb)> file prior to v1.23 release.
*** NOTE: for v1.23 only, a modified version of usher was used; this modified version is expected to become usher version 0.6.3.  It has a bugfix for a corner case that affects only samples whose best placement is at the root node, which for pangolin is lineage A, and the v1.23 tree triggers the bug in more cases than the previous trees which is why the bug was not discovered until this release.
If …
=> Prerelease v1.23

pangolin_assignment/__init__.py
pangolin-data v1.23.1 minor release adds JQ to alias_key.json, which has no effect on the cached lineage assignments; pangolin-data's alias_key.json is used only for comparison of inference lineage (from usher) with scorpio assignment.
=> Minor release v1.23.1 to stay in sync with pangolin-data

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.26 on GISAID sequences downloaded through 2024-03-08
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.26 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.26/pangolin_data/data/lineageTree.pb)> file prior to v1.26 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.26

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.27 on GISAID sequences downloaded through 2024-04-24
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.27 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.27/pangolin_data/data/lineageTree.pb)> file prior to v1.27 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.27

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.28 on GISAID sequences downloaded through 2024-06-21
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.28 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.28/pangolin_data/data/lineageTree.pb)> file prior to v1.28 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.28

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.28 on GISAID sequences downloaded through 2024-07-01, rebuilt for pangolin-data and pangolin-assignment release v1.28.1 (minor release to fix accidental inclusion of KR.2, see https://github.com/cov-lineages/pangolin-data/issues/60).
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.28.1 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.28.1/pangolin_data/data/lineageTree.pb)> file prior to v1.28.1 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.28.1

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.29 on GISAID sequences downloaded through 2024-07-26
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.29 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.29/pangolin_data/data/lineageTree.pb)> file prior to v1.29 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.29

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.30 on GISAID sequences downloaded through 2024-09-19
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.30 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.30/pangolin_data/data/lineageTree.pb)> file prior to v1.30 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.30

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.31 on GISAID sequences downloaded through 2024-11-19
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.31 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.31/pangolin_data/data/lineageTree.pb)> file prior to v1.31 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.31

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.32 on GISAID sequences downloaded through 2025-01-23
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.32 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.32/pangolin_data/data/lineageTree.pb)> file prior to v1.32 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.32

pangolin_assignment/__init__.py, pangolin_assignment/usher_assignments.cache.csv.gz
Assignment cache from pango-designation v1.33.1 on GISAID sequences downloaded through 2025-03-19
The cache was computed at UCSC on sequences downloaded from [GISAID](https://gisaid.org/), using pangolin with the `--skip-scorpio` flag and `--usher-tree` <[v1.33 lineageTree.pb](https://github.com/cov-lineages/pangolin-data/blob/v1.33/pangolin_data/data/lineageTree.pb)> file prior to v1.33 release.
```
usher 0.6.3
gofasta 1.2.1
faToVcf: 448
```
=> pangolin-assignment v1.33
